app/main/forms.py
# -*- coding: utf-8 -*-
from flask import request
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import ValidationError, DataRequired, Length
from flask_babel import _, lazy_gettext as _l
from app.models import User

class SearchForm(FlaskForm):
    q = StringField(_l('Поиск'), validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        if 'formdata' not in kwargs:
            kwargs['formdata'] = request.args
        if 'csrf_enabled' not in kwargs:
            kwargs['csrf_enabled'] = False
        super(SearchForm, self).__init__(*args, **kwargs)

class EditProfileForm(FlaskForm):
    username = StringField(_l('Имя пользователя'), validators=[DataRequired()])
    about_me = TextAreaField(_l('Обо мне'), validators=[Length(min=0, max=140)])
    submit = SubmitField(_l('Отправить'))

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError(_l('Пожалуйста используйте другое имя пользователя.'))

class PostForm(FlaskForm):
    post = TextAreaField(_l('Скажите что-нибудь'), validators=[DataRequired(), Length(min=1, max=140)])
    submit = SubmitField(_l('Отправить'))

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, template_folder='templates')

from app.main import routes

app/main/routes.py
# -*- coding: utf-8 -*-
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, g, \
    jsonify, current_app
from flask_login import current_user, login_required
from flask_babel import _, get_locale
from guess_language import guess_language
from app import db
from app.main.forms import EditProfileForm, PostForm, SearchForm
from app.models import User, Post
from app.translate import translate
from app.main import bp

@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    form = PostForm()
    if form.validate_on_submit():
        language = guess_language(form.post.data)
        if language == 'UNKNOWN' or len(language) > 5:
            language = ''
        post = Post(body=form.post.data, author=current_user, language=language)
        db.session.add(post)
        db.session.commit()
        flash(_('Ваше сообщение опубликовано!'))
        return redirect(url_for('main.index'))
    page = request.args.get('page', 1, type=int)
    posts = current_user.followed_posts().paginate(page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('main.index', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('main.index', page=posts.prev_num) \
        if posts.has_prev else None
    return render_template('index.html', title=_('Главная страница'), form=form, posts=posts.items, next_url=next_url, prev_url=prev_url)

@bp.route('/explore')
@login_required
def explore():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('main.index', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('main.index', page=posts.prev_num) \
        if posts.has_prev else None
    return render_template('index.html', title=_('Исследование'), posts=posts.items, next_url=next_url, prev_url=prev_url)


@bp.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('main.user', username=user.username, page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('main.user', username=user.username, page=posts.prev_num) \
        if posts.has_prev else None
    return render_template('user.html', user=user, posts=posts.items, next_url=next_url, prev_url=prev_url)

@bp.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
        g.search_form = SearchForm()
    g.locale = str(get_locale())

@bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash(_('Ваши изменения были сохранены.'))
        return redirect(url_for('main.edit_profile'))
    elif request.method=='GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', title=_('Редактировать профиль'), form=form)

@bp.route('/follow/<username>')
@login_required
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash(_('Пользователь %(username)s не найден.', username=username))
        return redirect(url_for('main.index'))
    if user == current_user:
        flash(_('Вы не можете подписаться на себя!'))
        return redirect(url_for('main.user', username=username))
    current_user.follow(user)
    db.session.commit()
    flash(_('Вы подписались на %(username)s!', username=username))
    return redirect(url_for('main.user', username=username))

@bp.route('/unfollow/<username>')
@login_required
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash(_('Пользователь %(username)s не найден.',username=username))
        return redirect(url_for('main.index'))
    if user == current_user:
        flash(_('Вы не можете отписаться от себя!'))
        return redirect(url_for('main.user', username=username))
    current_user.unfollow(user)
    db.session.commit()
    flash(_('Вы отписались от %(username)s.', username=username))
    return redirect(url_for('main.user', username=username))

@bp.route('/search')
@login_required
def search():
    if not g.search_form.validate():
        return redirect(url_for('main.explore'))
    page = request.args.get('page', 1, type=int)
    posts, total = Post.search(g.search_form.q.data, page, current_app.config['POSTS_PER_PAGE'])
    next_url = url_for('main.search', q=g.search_form.q.data, page=page + 1) \
        if total > page * current_app.config['POSTS_PER_PAGE'] else None
    prev_url = url_for('main.search', q=g.search_form.q.data, page=page - 1) \
        if page > 1 else None
    return render_template('search.html', title=_('Поиск'), posts=posts, next_url=next_url, prev_url=prev_url)

@bp.route('/translate', methods=['POST'])
@login_required
def translate_text():
    return jsonify({'text': translate(request.form['text'], request.form['source_language'], request.form['dest_language'])})

app/main/templates/_post.html
<table class="table table-hover">
    <tr>
        <td width="70px">
            <a href="{{ url_for('main.user', username=post.author.username) }}">
                <img src="{{ post.author.avatar(70) }}" />
            </a>
        </td>
        <td>
            {% set user_link %}
            <a href="{{ url_for('main.user', username=post.author.username) }}">
                {{ post.author.username }}
            </a>
            {% endset %}
            {{ _('%(username)s сказал(а): %(when)s', username=user_link, when=moment(post.timestamp).fromNow()) }}:
            <br>
            <span id="post{{ post.id }}">{{ post.body }}</span>
            {% if post.language and post.language != g.locale %}
            <br><br>
            <span id="translation{{ post.id }}">
                <a href="javascript:translate('#post{{ post.id }}',
                            '#translation{{ post.id }}'
                            '{{ post.language }}',
                            '{{ g.locale }}');">{{ _('Translate') }}</a>
            </span>
            {% endif %}
        </td>
    </tr>
</table>

app/main/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {% if title %}{{ title }} - {{ _('Микроблог') }}{% else %}{{ _('Добро пожаловать в Микроблог') }}{% endif %}
{% endblock %}

{% block navbar %}
 <nav class="navbar navbar-default">
 <div class="container">
 <div class="navbar-header">
    <type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
 <span class="sr-only">Toggle navigation</span>
 <span class="icon-bar"> > </span>
 <span class= "icon-bar"> > </span>
 <span class="icon-bar"> > </span>
 </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">{{ _('Микроблог') }}</a>
 </div>
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">{{ _('Домашняя') }}</a></li>
                    <li><a href="{{ url_for('main.explore') }}">{{ _('Исследование') }}</a></li>
    </ul>
    {% if g.search_form %}
    <form class="navbar-form navbar-left" method="get" action="{{ url_for('main.search') }}">
        <div class="form-group">
            {{ g.search_form.q(size=20, class='form-control', placeholder=g.search_form.q.label.text) }}
        </div>
    </form>
    {% endif %}
    <ul class="nav navbar-nav navbar-right">
      {% if current_user.is_anonymous %}
                    <li><a href="{{ url_for('auth.login') }}">{{ _('Вход') }}</a></li>
 {% else %}
                    <li><a href="{{ url_for('main.user', username=current_user.username) }}">{{ _('Профиль') }}</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">{{ _('Выход') }}</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# контент приложения должен быть предоставлен в блоке app_content #}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.lang(g.locale) }}
    <script>
        function translate(sourceElem, destElem, sourceLang, destLang) {
            $(destElem).html('<img src="{{ url_for('static', filename='loading.gif') }}">');
            $.post('/translate', {
                text: $(sourceElem).text(),
                source_language: sourceLang,
                dest_language: destLang
            }).done(function(response) {
                $(destElem).text(response['text'])
            }).fail(function() {
                $(destElem).text("{{ _('Ошибка: не удалось связаться с сервером.') }}");
            });
        }
    </script>
{% endblock %}

app/main/templates/edit_profile.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ _('Редактировать профиль') }}</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/main/templates/index.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ _('Здравствуй, %(username)s!', username=current_user.username) }}</h1>
{% if form %}
 {{ wtf.quick_form(form) }}
 <br>
 {% endif %}
 {% for post in posts %}
 {% include '_post.html' %}
 {% endfor %}
 <nav aria-label="...">
 <ul class= "pager">
 <li class="previous{% if not prev_url %} disabled{% endif %}">
 <a href="{{ prev_url or '#' }}">
 <span aria-hidden="true">&larr;</span> {{ _('Новые сообщения') }}
 </a>
 </li>
 <li class="next{% if not next_url %} disabled{% endif %}">
 <a href="{{ next_url or '#' }}">
                    Старые сообщения <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/main/templates/search.html
{% extends "base.html" %}

{% block app_content %}
    <h1>{{ _('Результаты поиска') }}</h1>
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span>
                    {{ _('Предыдущие результаты') }}
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    {{ _('Следующие результаты') }}
                    <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/main/templates/user.html
{% extends "base.html" %}

{% block app_content %}
 <table class="table table-hover">
<tr>
 <td width="256px"><img src="{{ user.avatar(256) }}"></td>
 <td>
                <h1>{{ _('Пользователь') }}: {{ user.username }}</h1>
                {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
                {% if user.last_seen %}
                <p>{{ _('Был в сети') }}: {{ moment(user.last_seen).format('LLL') }}</p>
                {% endif %}
                <p>{{ _('%(count)d - подписчиков', count=user.followers.count()) }}, {{ _('%(count)d - подписок.', count=user.followed.count()) }}</p>
                {% if user == current_user %}
                <p><a href="{{ url_for('main.edit_profile') }}">{{ _('Редактировать профиль') }}</a></p>
                {% elif not current_user.is_following(user) %}
                <p><a href="{{ url_for('main.follow', username=user.username) }}">{{ _('Подписаться') }}</a></p>
                {% else %}
                <p><a href="{{ url_for('main.unfollow', username=user.username) }}">{{ _('Отписаться') }}</a></p>
                {% endif %}
            </td>
        </tr>
    </table>
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> {{ _('Новые сообщения') }}
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    {{ _('Старые сообщения') }} <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}